---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        prometheus.io.scrape: 'true'
    spec:
      serviceAccountName: ingress-operator
      containers:
      - name: operator
        image: functions/ingress-operator:0.1.0
        imagePullPolicy: Always
        command:
          - ./ingress-operator
          - -logtostderr
          - -v=2
        env:
        - name: function_namespace
          value: openfaas
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
